version: "3.9"

services:
  database:
    container_name: cobenefito_db
    image: mariadb:10.5
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=cobenefito
    volumes:
      - ./backend/db-data:/var/lib/mysql
    ports:
      - "33061:3306"

  backend:
    container_name: cobenefito_be
    environment:
      - RAILS_ENV=development
      - DB_HOST=database
      - DB_USERNAME=admin
      - DB_PASSWORD=password
      - DB_DATABASE=cobenefito
      - SECRET=secret
      - CLIENT_URL=http://localhost:8000
      - EMAIL_ACCOUNT=tunadate.test@gmail.com
      - EMAIL_USERNAME=tunadate.test
      - EMAIL_PASSWORD=
    build:
      context: ./backend
      dockerfile: Dockerfile.stg
    # volumes:
    #   - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    stdin_open: true
    tty: true

  frontend:
    container_name: cobenefito_fe
    environment:
      - API_BASE_URL=http://localhost:3000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

