require: 
  - rubocop-rails

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 50

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false
