name: backend-test-flow

on: 
  pull_request:
    branches:
      - master

env:
  RUBY_VERSION: 2.7.5
  DB_HOST: '127.0.0.1'
  DB_ROOT_PASSWORD: 'password'
  DB_USERNAME: 'admin'
  DB_PASSWORD: 'password'
  DB_DATABASE: 'cobenefito'
  DB_DATABASE_TEST: 'cobenefito_test'
  SECRET: 'secret'
  RAILS_ENV: 'test'
  DB_SOCKET: '/run/mysqld/mysqld.sock'

jobs:
  # code-format-validation:
  #   name: Rubocop testing
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}
  #     - name: Install rubocop
  #       run: gem install rubocop-rails
  #     - name: Checkcode
  #       run: cd backend && rubocop

  code-test-validation:
    name: Rspec testing
    # needs: code-format-validation
    runs-on: ubuntu-20.04
    services:
      database:
        image: mariadb:10.5
        env:
          MARIADB_ROOT_PASSWORD: ${{ env.DB_ROOT_PASSWORD }}
          MARIADB_USER: ${{ env.DB_USERNAME }}
          MARIADB_PASSWORD: ${{ env.DB_PASSWORD }}
          MARIADB_DATABASE: ${{ env.DB_DATABASE_TEST }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/cache@v1
        with:
          path: backend/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: | 
            ${{ runner.os }}-gems-
      - name: verify mariadb connection
        run: |
          sudo apt-get install -y mysql-client libmysqlclient-dev
          mysql -h 127.0.0.1 -u ${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE_TEST }}
      - name: bundle install and create db
        run: |
          cd backend
          gem install bundler --version 2.1.4
          bundle config path vendor/bundle
          bundle install
          bin/rails db:prepare
      - name: run test
        run: cd backend && bundle exec rspec

        
      
